import { Inter } from "next/font/google";
import TodoApp from "../components/TodoApp"
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TodoApp/>
        {children}
        </body>
    </html>
  );
}
